### PR TITLE
To Do list: interactive list

### PR DESCRIPTION
**Pull request by billymohajeri**
In this step I,

- Added a new JavaScript file and import it as a module.
- Added methods related to the status updates (completed: true / false).
- Added event listener to the checkbox (change).
- Updated items object's value for completed key upon user actions.
- Implemented a function for the "Clear all completed" button.
- Stored the updated array of items in local storage.
- Added styling for the done tasks.

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @billymohajeri, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - No linter errors. ✔️
 - Clean and organized code. ✔️ 
 - Professional PR message. ✔️ 

## Aspects to improve ♻️

- [ ] Check the comments under the review.
- [ ] Your crud functions are working almost as expected. The only issue I found is when the user tries to remove a todo and immediately reloads the page. When a todo is removed, the correct todo is removed from the page, but in the local storage, the first todo is removed, and when the user immediately reloads the page the list changes on the page. Kindly fix this bug.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by billymohajeri** [comment]
Hi @leonardodiasb,
Thank you for your feedback. Actually, I couldn't see the problem. So when I remove any item, the correct item removes from both the page and storage. Then I reorder the index of the elements from 1 to end.

Is it possible to record a short video to demonstrate the issue?
Thanks again

**Comment by medaminedev66** [comment]
Hello @billymohajeri  👋,

_This is an additional review as a result of the second opinion request._

Your project is almost complete, I tested your app and I think the only issue is when the user clicks on the "Clear all completed" button, your app does not update all remaining items' indexes, so they represent the current list order and are unique. Kindly fix this issue so that your project is complete

I also recommend fixing your webpack setup so that the reviewers are able to run your project. I recommend adding the following line to Scripts section in package.json so that your project can be started by "npm start":
```json
"start": "webpack serve --open",
```

Keep rocking 🚀!

**Review by Yazino12 — APPROVED** [review]
## Hi @billymohajeri 🖐🏾,

You have done a great job adding the changes requested by a previous reviewer 🎯, and there is nothing else left to do other than it's time to merge it 🚀🚀.

### To Highlight:
- Descriptive pull request title and summary ✔
- Correct use of GitHub flow ✔
- Organized code ✔

# STATUS: APPROVED ✅✅✅
CLAP
_Check the comments under the review 👇🏽👇🏽👇🏽._

## Optional suggestions
- **_[OPTIONAL]_** In your future projects please use [this template](https://github.com/microverseinc/readme-template) and remember that all sections are mandatory except the [FAQ](https://github.com/microverseinc/readme-template#:~:text=%E2%9D%93-,FAQ,-Add%20at%20least) in order to present your project with as much detail as possible 🤝🏽.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @Yazino12 when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
